deployment:
  tasks:
    - export DEPLOYPATH=/home/gmac9439/public_html/sekolahsabat.my.id/

    # Salin file individu dengan logging
    - /bin/cp .editorconfig $DEPLOYPATH && echo "$(date) - Copied .editorconfig" >> /home/gmac9439/deploy.log
    - /bin/cp .gitignore $DEPLOYPATH && echo "$(date) - Copied .gitignore" >> /home/gmac9439/deploy.log
    - /bin/cp composer.json $DEPLOYPATH && echo "$(date) - Copied composer.json" >> /home/gmac9439/deploy.log
    - /bin/cp index.php $DEPLOYPATH && echo "$(date) - Copied index.php" >> /home/gmac9439/deploy.log
    - /bin/cp LICENSE $DEPLOYPATH && echo "$(date) - Copied LICENSE" >> /home/gmac9439/deploy.log
    - /bin/cp license.md $DEPLOYPATH && echo "$(date) - Copied license.md" >> /home/gmac9439/deploy.log
    - /bin/cp readme.md $DEPLOYPATH && echo "$(date) - Copied readme.md" >> /home/gmac9439/deploy.log

    # Salin semua file dan folder lain kecuali file konfigurasi sensitif
    - /bin/cp -R . $DEPLOYPATH && echo "$(date) - Copied all files and directories" >> /home/gmac9439/deploy.log

    # Hapus file konfigurasi sensitif yang mungkin ter-copy
    - rm -f $DEPLOYPATH/application/config/database.php && echo "$(date) - Removed database.php from deployment" >> /home/gmac9439/deploy.log
    - rm -f $DEPLOYPATH/application/config/config.php && echo "$(date) - Removed config.php from deployment" >> /home/gmac9439/deploy.log

    # Catat kesalahan atau status akhir
    - echo "$(date) - Deployment completed" >> /home/gmac9439/deploy.log
