deployment:
  tasks:
    - export DEPLOYPATH=/home/gmac9439/public_html/sekolahsabat.my.id/

    # Salin file individu dengan logging
    - /bin/cp .editorconfig $DEPLOYPATH && echo "$(date) - Copied .editorconfig" >> /home/gmac9439/deploy.log
    - /bin/cp .gitignore $DEPLOYPATH && echo "$(date) - Copied .gitignore" >> /home/gmac9439/deploy.log
    - /bin/cp composer.json $DEPLOYPATH && echo "$(date) - Copied composer.json" >> /home/gmac9439/deploy.log
    - /bin/cp index.php $DEPLOYPATH && echo "$(date) - Copied index.php" >> /home/gmac9439/deploy.log
    - /bin/cp LICENSE $DEPLOYPATH && echo "$(date) - Copied LICENSE" >> /home/gmac9439/deploy.log
    - /bin/cp license.md $DEPLOYPATH && echo "$(date) - Copied license.md" >> /home/gmac9439/deploy.log
    - /bin/cp readme.md $DEPLOYPATH && echo "$(date) - Copied readme.md" >> /home/gmac9439/deploy.log
    - /bin/cp htaccess_forwebsite $DEPLOYPATH && echo "$(date) - Copied htaccess_forwebsite" >> /home/gmac9439/deploy.log

    # Salin direktori menggunakan cp
    - /bin/cp -R application $DEPLOYPATH && echo "$(date) - Copied directory application" >> /home/gmac9439/deploy.log
    - /bin/cp -R assets $DEPLOYPATH && echo "$(date) - Copied directory assets" >> /home/gmac9439/deploy.log
    - /bin/cp -R system $DEPLOYPATH && echo "$(date) - Copied directory system" >> /home/gmac9439/deploy.log

    # Catat kesalahan atau status akhir
    - echo "$(date) - Deployment completed" >> /home/gmac9439/deploy.log
